
logging:
  file:
    name: app.log
  pattern:
    dateformat: dd-MM-yyyy hh:mm:ss    
  level:
    root: WARN
    com.sebrown.app: INFO

resource: 
  path: .

persistance:
  type: file
  
vendor:
    namesfile:  VendorNames.txt
    accronymfile:  VendorAccronyms.txt
 
app:    
    
  maxsheetnamelen: 22
  minsheetnamelen: 3
  mappings:
    vendor: vendor-mapping-ws.txt #TODO - NOT USING THIS? CHECK & REMOVE
    
  workbooks:
    auditIn:
      name: Audit In
      nameStartsWith: ISO-Audit
      sheets:
        installedApps:
          name: Installed Apps      
          columnMappings:
            description: 0
            identifyingNumber: 1
            installDate: 2
            name: 3
            productId: 4
            regCompany: 5
            regOwner: 6
            vendor: 7
            version: 8
        systemInfo:
          name: System Info
    
    auditOut:
      name: Installed Software.xlsx
      nameStartsWith: 
      sheets:
        vendorNotFound:
          name: Vendor Not Found      
          columnMappings:
            id: 0
            name: 1
            identifyingNumber: 2
            version: 3
            installedAssetIDs: 4
                  