
props:

  resource: 
    path: src/test/resources/
    
  test:
    
    unit:
      wbpath: src/test/resources/
      wbname: ISO-Audit-Test-26-08-22_08-47-37.xlsm
      auditworkbookpath: ./src/test/resources/Installed Software.xlsx
      auditedworkbookpath: src/test/resources/
      
    integration:
      resource: src/test/resources/integration