
logging:
  file:
    name: app.log
  pattern:
    dateformat: dd-MM-yyyy hh:mm:ss    
  level:
    root: WARN
    com.sebrown.app: INFO

app:

  resource: 
    path: .
    
  mappings:
    vendor: vendor-mapping-ws.txt
    
  workbooks:
    auditIn:
      name: Audit In
      nameStartsWith: ISO-Audit
      sheets:
        installedApps:
          name: Installed Apps      
          columnMappings:
            description: 1
            identifyingNumber: 2
            installDate: 3
            name: 4
            productId: 5
            regCompany: 6
            regOwner: 7
            vendor: 8
            version: 9
        systemInfo:
          name: System Info
    
    auditOut:
      name: Installed Software.xlsx
      nameStartsWith: 
      sheets:
        vendorNotFound:
          name: Vendor Not Found      
          columnMappings:
            id: 1
            name: 2
            identifyingNumber: 3
            version: 4
            installedAssetIDs: 5
                  